### ISSUE TITLE
Initiative with a gunslinger and using the feat: alert

### ISSUE THREAD

**Issue by bryanalfsib** [morepurplemorebetter/MPMBs-Character-Record-Sheet#1]
Hello, 
I am using the pdf character creator (really nice). The character I was creating is a human variant gunslinger (Matt Mercer version). The feat chosen for the human variant was Alert (+5 initiative), and this seems to be working until the character reaches lvl 7, in which due to a class skill the character also adds its proficiency bonus to the initiative. At lvl 1 the initiative is calculated correctly, but at lvl 7 the pdf will take precedence to the recently change modifier rather than add it all together.
eg: Dex 16-Mod +3
lvl with alert
Initiative = +8
lvl 7- Class skill
Initiative = +6
(if I change the feat to something else and change back)
Initiative = +8

**Comment by morepurplemorebetter** [comment]
So I didn't notice that I had new messages on GitHub. Didn't even know anybody was using this for commenting on my sheets. So please excuse me for the late reply.

The sheet isn't set up to add more than a single modifier to initiative. So when a new things comes along that adds a modifier, it will overwrite the previous modifier. So when you select the Alert feat it will make it a +5, but then whenever your level changes, the sheet will force the modifier to be your proficiency bonus.

Each time you change level, you will have to manually change the content of the initiative modifier. (which is part of the 'Modifier' fields on the Printer Friendly version, but you didn't say which type and version of the sheet you use.)

As this is concerning a fan-made addition script, and not a core function of the sheet, I will not make a work-around for this. I find it very unlikely that WotC will create a class feature for adding your proficiency bonus to initiative as that is something I find unbalanced.
