### ISSUE TITLE
Usages Calc on Racial Feature

### ISSUE THREAD

**Issue by mouse0270** [morepurplemorebetter/MPMBs-Character-Record-Sheet#11]
When using `usagescalc` on a racial feature, it just displays the text and not the actual calculation.

``` javascript
features : {
	"primal bite fire" : {
		name : "Primal Bite (Fire)",
		source : ["P", 72],
		minlevel : 1,
		usages : "Constitution modifier per ",
		usagescalc : "event.value = Math.max(1, tDoc.getField(\"Con Mod\").value);",
		description : "\n I can make a bite attack that deals 1d6 fire damage.",
		additional : ["1d6", "1d6", "1d6", "1d6", "1d6", "2d6", "2d6", "2d6", "2d6", "2d6", "3d6", "3d6", "3d6", "3d6", "3d6", "4d6", "4d6", "4d6", "4d6", "4d6"],
		recovery : "short rest",
		action : ["bonus action", ""]
	}
}
```

In the uses column it shows (`Constitution modifier`)

**Comment by mouse0270** [comment]
So it appears after looking though your code, that the `usagescalc` is a class only feature. :(

**Comment by morepurplemorebetter** [comment]
I have made it possible to use `usagescalc` with racial features now as well, [with the latest update](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/commit/6d388224e40cc1d7a41345a07295e0675ad53019#diff-bd12c4e008b90968b1dc176243324ff0R5794). However, the racial features and class features still differ greatly in what you can do with them, just FYI.
