### ISSUE TITLE
Add Echo Knight please.

### ISSUE THREAD

**Issue by TheDCM15** [morepurplemorebetter/MPMBs-Character-Record-Sheet#111]
On second thought, can you guys add all the new books to the character sheets?

**Comment by morepurplemorebetter** [comment]
This repository can only hold the content from the System Reference Document as any other content is copyright of Wizards of the Coast. Please use the "Issues" page on GitHub for problems with the code and not for content or feature requests. For that, please see the Discord channel: https://discord.gg/Qjq9Z5Q
