### ISSUE TITLE
Monster Hunter Pack is Missing

### ISSUE THREAD

**Issue by mouse0270** [morepurplemorebetter/MPMBs-Character-Record-Sheet#12]
I noticed you have alot of the stuff from CoS but it appears you are missing the Monster Hunter pack. 

```
Monster Hunter’s Pack
You can buy a monster hunter’s pack for 33 gp, which is cheaper than buying the items in 
it individually. It includes a chest, a crowbar, a hammer, three wooden stakes, a holy symbol, 
a flask of holy water, a set of manacles, a steel mirror, a flask of oil, a tinderbox, and 3 
torches.
```

**Comment by morepurplemorebetter** [comment]
You are right, that pack is missing. However, until I have made a way of including/excluding packs/gear/tools based on source, I have no intention of adding material that is not both official and playtested.
