### ISSUE TITLE
add Foreclaimer to sheet

### ISSUE THREAD

**Issue by Ingolx** [morepurplemorebetter/MPMBs-Character-Record-Sheet#120]
halo I have tryed to make a scripet for the Foreclaimer race from folls gold it comes op with the error ''ReferenceError:
invalid assignment left-hand side'' im new to coding its based on the script for the dragonborn thanks for the help
 [forclaimer script.txt](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/files/8400493/forclaimer.script.txt)

**Comment by morepurplemorebetter** [comment]
This is not the place to ask for help with your custom import script. This is for reporting issues with the base code of the sheet. Please use the [/r/mpmb subreddit ](https://www.reddit.com/r/mpmb/)or [MPMB Discord server](https://discord.gg/CnCuxyV) instead.

You script has several basic JavaScript syntax issues. Running it through a service like jshint.com should help you solve most of these issues.

For questions about the MPMB syntax, please see the aforementioned forums.
