### ISSUE TITLE
Equipment Costs

### ISSUE THREAD

**Issue by Ebaninth** [morepurplemorebetter/MPMBs-Character-Record-Sheet#122]
How do I assign a cost for Armor...and for items generally?

I have just created my own HB armour & weapon list, but cannot find how I can change the actual cost of these?

**Comment by morepurplemorebetter** [comment]
The sheet doesn't have any automation for cost of items (yet). The only place where item cost is currently used is for entries in the `PacksList` and `GearList` objects. There, the cost is part of the `name` (PacksList) or `infoname` (GearList) attribute as that attribute is used to populate the menu you see when the Add Equipment button is pressed.

You can see the base objects (i.e. the static reference before import scripts are added) in [the ListsGear.js file](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/blob/master/_variables/ListsGear.js)
