### ISSUE TITLE
weapon proficiencies migration from old pdf to 12-95

### ISSUE THREAD

**Issue by erickrause** [morepurplemorebetter/MPMBs-Character-Record-Sheet#13]
I have a level 1 fighter that I built with a pdf in the last month.  Not sure which version of the pdf.  I tried the import into the latest pdf and none of the weapon and armor proficiencies moved across.  

I also just noticed that the Variant Human didn't come across.  The text was all set correctly, but I had to reselect it for the description in the ability score Javascript window.

Also, it's the print friendly version for both.

**Comment by morepurplemorebetter** [comment]
In order for me to have any idea where to start looking into this bug, I would have to know the version number of the sheet you are importing from. You can find the version number on the bottom over every page, and in the document's properties (File >> Properties... Ctrl+D).

However, I tried to reproduce this issue with several version of the sheet now and can't find anything that is going wrong like you describe. So it might just be best if you can send me a copy of the sheet you are trying to import from.

**Comment by erickrause** [comment]
I'm sorry I couldn't find the version number before.  I forgot that it was on the bottom of the page.
MorePurpleMoreBetter's D&D 5th edition Character Record Sheet v12.93 (Printer Friendly - Redesign)
This was the one imported into:
MorePurpleMoreBetter's D&D 5th edition Character Record Sheet v12.95 (Printer Friendly - Redesign)

I've been doing my migrations using the Import Directly from PDF ever since I saw the chance in the Changelog

I can't seem to be able to recreate the proficiencies migration bug.  I'm sorry you spent any time running that down.

I am still seeing the variant Human Racial Trait not come across as selected.  The text is correct, but the option under Racial Options isn't correct.  As far as I can tell this only impacts the text on the Ability Score Window.

Again, I'm sorry you spent the time trying to run down a bug that I can't reproduce now.

I've attached my sheet that I was importing from should you want to take a look.

[Talen (Eric).pdf](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/files/952411/Talen.Eric.pdf)

**Comment by morepurplemorebetter** [comment]
Thank you for giving some more details about the Variant Human bug. I was able to recreate it and [I found a way to fix it](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/blob/master/_functions/FunctionsImport.js#L577-L578). You can expect it to be patched in the next version of the sheet!

And I guess we will call the proficiencies not importing a fluke ;)
