### ISSUE TITLE
Sea Sorcerer's ability Watery Defense incorrect in v12.97

### ISSUE THREAD

**Issue by robinsving** [morepurplemorebetter/MPMBs-Character-Record-Sheet#15]
[UP: SO](http://media.wizards.com/2017/dnd/downloads/26_UASorcererUA020617s.pdf)

> **Watery Defense**
> [...]As a reaction when you are hit by an attack and take bludgeoning, piercing, or slashing damage from 
> it, you can reduce that damage by an amount equal to your sorcerer level plus your Charisma _score_ [...]. 
> 

A lot of sites made the same mistake; it has been confirmed to be score, not modifier, by [an official Tweet.](http://www.sageadvice.eu/2017/02/07/sea-sorcery-watery-defense-did-you-mean-charisma-modifier/)

**Comment by morepurplemorebetter** [comment]
Thank you for reporting this error. [It has now been fixed](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/commit/0b6ddf789844206e9bf6619d9fee52d71bd36ffa), and this fix will be included in the next version.
