### ISSUE TITLE
Handaxe Stats don't fill Automatically

### ISSUE THREAD

**Issue by fiamonci** [morepurplemorebetter/MPMBs-Character-Record-Sheet#16]
Hi, I noticed that when I select the Handaxe in the "Attacks: Weapons & Cantrips" section the stats are not automatically filled like the other Weapons.
[Barbarian - Handaxe Error.pdf](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/files/986623/Barbarian.-.Handaxe.Error.pdf)

**Comment by morepurplemorebetter** [comment]
Thank you for reporting this error. The code for it has already been fixed ([here](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/commit/1fb1b7a5bc2bbe601676d9bb8a6011ee0732b109#diff-6f190bef082527e490560dde80a87d1fR306)) and will be implemented in the next version of the sheet.

Until that time, you can get both the handaxe and battleaxe to work by writing 'axe' as a separate word. So as "Hand Axe" and "Battle Axe".
