### ISSUE TITLE
[question] How do you build this project into the working PDF?

### ISSUE THREAD

**Issue by TheKrush** [morepurplemorebetter/MPMBs-Character-Record-Sheet#18]
I was looking to use this amazing PDF you created with some homebrew modifications to the core classes. How do I take this repo and turn it into the working PDF? I'm not familiar with creating PDF files with javascript functions in them.

Might also be worth describing the steps for doing this on the project README as well.

Thanks.

**Comment by morepurplemorebetter** [comment]
You can't make the PDF from this repo. The PDF has form fields that also have JS actions attached to them that are not part of the repo.

You need the original PDF, which is available for free on [DMs Guild](http://flapkan.com/mpmb/dmsguild).

If you want to edit the JavaScript in the PDF, you will need Adobe Acrobat Pro.

However, as you only want to change the core classes, you can just use the "Add Custom Script" functionality, see the bookmark by the same name in the PDF. There you can add the class JSON and have it overwrite the built-in JSON. Any code you add in the "Add Custom Script" dialogue is run during opening of the sheet, after all the built-in JS has ran.

**Comment by TheKrush** [comment]
Oh it overwrites it, cool 👍
