### ISSUE TITLE
Ranger Companion: Wolf -- attack calculation incorrect

### ISSUE THREAD

**Issue by Ry7n** [morepurplemorebetter/MPMBs-Character-Record-Sheet#2]
Wolves have 12 STR and 15 DEX, and have +4 to hit, +2 to damage, so it appears that their bite attack uses Dexterity, not Strength.

DM's basic rules:

<img width="419" alt="screen shot 2017-02-24 at 8 12 16 am" src="https://cloud.githubusercontent.com/assets/23838/23310943/1d679e5e-fa69-11e6-9cef-4c3bc4762bd5.png">

However, MPMB sheet is calculating the ranger companion attack as STR + Proficiency + Ranger's Proficiency, causing it to be +5 instead of +6. The same issue occurs with damage.

<img width="589" alt="screen shot 2017-02-24 at 8 14 22 am" src="https://cloud.githubusercontent.com/assets/23838/23310977/47f49672-fa69-11e6-9881-b44d6a33ec60.png">

**Comment by morepurplemorebetter** [comment]
So I didn't notice that I had new messages on GitHub. Didn't even know anybody was using this for commenting on my sheets. So please excuse me for the late reply.

You are completely right about this. Thank you very much for reporting this issue and with such clear references.

I will make sure it uses Dex in the next version (v12.85)!
