### ISSUE TITLE
Missing comma on line 57 of Thieving Magpie

### ISSUE THREAD

**Issue by TwoHeadedBoy** [morepurplemorebetter/MPMBs-Character-Record-Sheet#20]
I just wanted to point out that there's a missing comma on line 57 of the Thieving Magpie subclass. I found out when I went to add it to my character's sheet.

**Comment by morepurplemorebetter** [comment]
Thank you for pointing this out, I totally missed it.

It is now fixed with [the latest commit](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/commit/d21f49935af04b481f93f9c77247c08b835bbd02) :)
