### ISSUE TITLE
Unarmored Defense (Barbarian 1, PHB 48) missing Shield / Misc Armor

### ISSUE THREAD

**Issue by TheKrush** [morepurplemorebetter/MPMBs-Character-Record-Sheet#21]
◆ Unarmored Defense (Barbarian 1, PHB 48)
   Without armor, my AC is 10 + Dexterity modifier + Constitution modifier + shield

If you make a Warforged (+1 armor 'Composite Plating') and use a shield the AC field still displays only:
10 + con + dex

It should be displaying:
10 + con + dex + shield + misc

**Comment by morepurplemorebetter** [comment]
Thank you for reporting any issues you find with the sheet!

However, I'm not able to replicate the problem that you are describing. Could you help me to reproduce it?

What version number of the sheet are you using and what type (A4, Printer Friendly)? And what software are you using to open the sheet with (Acrobat Pro, Reader, Standard) and what version number of that software?

Can you please tell me the steps to take, starting with a freshly downloaded sheet, to make this bug apparent?
Also, it would be helpful if you can send me a copy of the sheet with which you are having this issue. This can be through email (flapkan[at]gmail.com) or by uploading the sheet on a cloud sharing service (like google drive) and sending/posting a link to it.

**Comment by TheKrush** [comment]
12.993 is the version I had, let me check with the newest version.

**Comment by TheKrush** [comment]
Oh I figured out what it was, My dex was +4, con +3, shield +2, and composite plating +1. I was choosing Unarmored Defense not Unarmored Defense (Con) so it was adding shield/plating without constitution
