### ISSUE TITLE
Feature Request: Separate Column to add Ability Scores gained on level up.

### ISSUE THREAD

**Issue by RobRoseKnows** [morepurplemorebetter/MPMBs-Character-Record-Sheet#23]
Not sure if this is possible, I'd try to do it myself if I had the ability to edit PDFs, but I think a very good feature would be a separate columns of spin boxes to add stat increases gained from leveling up. I've been having trouble keeping track of all my ability score increases on each level.

**Comment by izulien** [comment]
Do you actually need it displayed on the PDF?  I typically add it to "Extra Bonus" column in the Ability Calculator. 
![image](https://user-images.githubusercontent.com/14319924/32693502-bbf803b2-c6f9-11e7-994b-00c978c942da.png)

**Comment by morepurplemorebetter** [comment]
I'm sorry I didn't respond to this sooner. @RobRoseKnows do you mean that you would want to see another column in the pop-up dialogue or a column on the printed sheet? @izulien is right that the "Extra" column is meant to be used for this exact purpose!

**Comment by nadcraker** [comment]
Maybe just renaming this column from Extra Bonus to Level Bonus or something would help with this? If indeed that was the intention for the column all along.

**Comment by RobRoseKnows** [comment]
Yeah I'd rename it to Level Bonus if that's the case.

**Comment by morepurplemorebetter** [comment]
Done!
