### ISSUE TITLE
Question. A creature/mount  that has arnor/barding

### ISSUE THREAD

**Issue by magnusprime27** [morepurplemorebetter/MPMBs-Character-Record-Sheet#27]
Looking at the warhorse there's a variant in the mm. For armor (barding).
How do you incorporate it into it's stat block?
Do you just change the account? Or do you need a special entry somewhere?

" I'm creating a Wartiger;
It uses the sabre-toothed tiger stats but has armor barding

**Comment by magnusprime27** [comment]
Sorry , auto correct. Account should say ac.

**Comment by morepurplemorebetter** [comment]
The CreatureList only has an AC entry and the Companion section has no way to incorporate different armours other than manually changing the AC field. You could make a warhorse entry in the CreatureList with the changed AC, but it would be far easier to just select the warhorse on the Companion page and then change its AC.

**Comment by magnusprime27** [comment]
Question,
When it comes to ability scores,
[0, 0, 0, 0, 0, 0]
If you have save +2 dex, +1 con.
Its [0. 1, 2, 0, 0, 0] written as 
" 'race': +2 Dexterity, +1 Constitution;"
Variant human is
[ 0 0 0 0 0 0]
Written:
"Human: +1 to two different scores of my choice;"

But what if I have a combination of both? 
+2 dex, +1 con, and +1 to one other score?
Written as,
" 'race' : +2 dex, +1 con, +1 to one other score of my choice;"
Or do they have to be a separate entries

**Comment by morepurplemorebetter** [comment]
The numbers in the array are separate from the text that you provide. You can have the numbers only be added to the fixed values and in the text say that you also get to add something to another value. [See the Half-Elf for an example of this](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/blob/master/_variables/ListsRaces.js#L172-L173).
