### ISSUE TITLE
Wild Shape Skill Issues by sort of skills on page 1.

### ISSUE THREAD

**Issue by LogosWorks** [morepurplemorebetter/MPMBs-Character-Record-Sheet#3]
I sent you a msg on Reddit and on GitHub.

I found there to be a bug with the interaction between wild shape and how skill proficiencies are sorted on page 1.

I will show you the skills for a wild shape riding horse because they do not have any skills making it simpler to see the issue.
When skills are sorted alphabetically both correctly show proficiency in Animal handling, Insight, Perception, Survival.
However when the skills on the front page are sorted by ability score, the front page correctly shows Animal handling, Insight, Perception, Survival.
The wild shape stat block is odd though, it shows Medicine, Nature, Performance, Persuasion.
I did find a fix as i was debugging it to send this msg to you. 

The wild shape skills are only messed up if they are calculated while the skills list is sorted by ability score. While it is annoying it is possible to sort skills alphabetically before any recalculations and then swap it back after. Perhaps something worth adding to the FAQ?

**Comment by morepurplemorebetter** [comment]
Hi LogosWork,

Although I didn't receive any message on Reddit, I appreciate the heads up about this bug. I will make sure to fix it in the next version. Thank you very much for reporting it!

The issue is simply that I forgot to have the wild shape code correct for a non-alphabetically sorted skills list.

**Comment by morepurplemorebetter** [comment]
I fixed it in v12.87, [here](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/commit/4acd1c1bf621db40593ffc706ee68bc21af0f9b6#diff-9576a7039c9c22f18008a1dbc8c1abf8R808)
