### ISSUE TITLE
RequiredSheetVersion() function does nothing...

### ISSUE THREAD

**Issue by safety-orange** [morepurplemorebetter/MPMBs-Character-Record-Sheet#30]
[This line](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/blob/master/_functions/FunctionsImport.js#L2172) should be `if (ScriptAtEnd.length > 0) ScriptsAtEnd = ScriptsAtEnd.concat(ScriptAtEnd);`.

I would send a PR, but that's not so easy on mobile ;)

**Comment by morepurplemorebetter** [comment]
Thank you for reporting this issue, it has now been fixed in the code. This code will be used in the next version of the sheet!
