### ISSUE TITLE
Sanity/Honor breaks Empty Passive Perception

### ISSUE THREAD

**Issue by TheIrishBandit** [morepurplemorebetter/MPMBs-Character-Record-Sheet#31]
Normally, when you use "Hide all fields as to print a truly empty sheet to fill out by hand", the Passive Perception box is blanked out. However, when you have Sanity or Honor enabled, it is not blanked out properly.

**Comment by morepurplemorebetter** [comment]
Thank you for reporting this issue. I have [fixed it here](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/commit/4d43c1b63755b1efddc48280118dbc5737a0a99b).

Thus, this will be fixed in the next version of the sheet :)
