### ISSUE TITLE
Wood Elf race features bug

### ISSUE THREAD

**Issue by djl9684** [morepurplemorebetter/MPMBs-Character-Record-Sheet#32]
Finding that the Wood Elf Race doesn't populate any of the subsequent fields.

I clicked quite a few others and it looks like the problem may only be with the wood elf.

**Comment by morepurplemorebetter** [comment]
The Wood Elf is not part of this Git. I'm guessing it is part of some kind of import into the sheet.

I would recommend contacting whomever you got the script from to notify them about the issues you are having.
