### ISSUE TITLE
Thing affecting the attack calculations has unidentified characters on Windows 7

### ISSUE THREAD

**Issue by Smashman** [morepurplemorebetter/MPMBs-Character-Record-Sheet#35]
![image](https://user-images.githubusercontent.com/2972388/34493697-027ecc62-efe5-11e7-8543-392185546101.png)

As you can see, the title font does not appear to be available and as such the characters appear as squares.

**Comment by morepurplemorebetter** [comment]
The font that is appearing as squares is the unicode font from your operating system, as that is what is used there. You will probably also notice a lot of these squares appearing in the field tooltips and the like. These are made by [this function](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/blob/master/_functions/Functions0.js#L497-L569), which changes an input string to their bold & italic unicode counterparts. 

This is not an issue with the sheet, but rather with your installation of Adobe Acrobat, your Operating System, or the font service of your machine. As such, I'm closing this issue.

However, maybe I can help to troubleshoot this if you tell me:
1) The operating system you are using, version, language, etc.
2) The version of Adobe Acrobat you are using, version number, type (Reader/Pro), language.

I have no issues with Windows 10 x64 Pro and Adobe Acrobat DC Pro (18.0092005) or Adobe Acrobat DC Reader (18.0092005).

I have seen this issue before on people using old version of Windows (XP or earlier), old version of Adobe Acrobat (X or earlier), and when trying to get the sheet to work on Linux.

**Comment by Smashman** [comment]
The issue only appears in this window. The field tooltips are fine, and I can copy the square into another area on my computer and they appear fine.

![image](https://user-images.githubusercontent.com/2972388/34494214-499a7fd6-efe7-11e7-8f69-99f7d57bea75.png)

I am on Windows 7 x64 Pro SP1 (English) with Adobe Acrobat Reader DC (18.009.20050.57426)

It's no big deal, I guess it's just a Windows 7 issue. :slightly_smiling_face:

**Comment by morepurplemorebetter** [comment]
Hmm, that is really rather strange Windows 7 behaviour indeed! Do you have the same issue in the spell sheet generation dialogues. Those have unicode on the top left where you can read how many spells the class knows and what the max spell level is that it can use.

**Comment by Smashman** [comment]
No it's fine there too. It must be the textbox being used.
![image](https://user-images.githubusercontent.com/2972388/34494992-097437ae-efeb-11e7-8ebb-bf7358455267.png)

**Comment by morepurplemorebetter** [comment]
For the attack calculation pop-up I use an edit-textbox that is set to read-only so that it will scroll if it is too long. Strange that that is somehow affecting the unicode. Maybe a bug to report to Adobe?
