### ISSUE TITLE
Plane Shift: Ixalan

### ISSUE THREAD

**Issue by Smashman** [morepurplemorebetter/MPMBs-Character-Record-Sheet#37]
New Plane Shift from Wizards.

~I've not gone over it all yet, but will endeavour to list the new stuff here soon.~

Will happily work on it with you, @morepurplemorebetter. 🙂

**Comment by Smashman** [comment]
Found here: https://media.wizards.com/2018/downloads/magic/plane-shift_ixalan.pdf

New Races:
- Merfolk
- Vampire
- Orc
- Goblin
- Siren


Note: Orc and Goblin races are different to Volo's and Human is present in the document, but is the same as standard PHB Human.

**Comment by Smashman** [comment]
The Vampire race in Ixalan appears to be a subrace of the Plane Shift Vampire race, first presented in Zendikar.
Zendikar Vampire conveys +1 Int and +2 Cha, whereas Ixalan Vampire conveys +1 Wis and +2 Cha. (Among other differences).

The Goblin race in Ixalan appears to be a subrace of the Plane Shift Goblin race, first presented in Zendikar.
Zendikar Goblin conveys +2 Con, whereas Ixalan Goblin conveys +2 Dex. (Among other differences).

The Merfolk race appears to be two additional Merfolk subraces for the original Merfolk race presented in Zendikar.
Subraces are as follows:
- Green Merfolk (+2 Wis, Mask of the Wild, Druid cantrip)
- Blue Merfolk (+ Int, Lore of the Waters, Wizard cantrip)

**Comment by Smashman** [comment]
New creatures:
- Frilled Deathspitter - CR 1/4
- Sunbird - CR 13
- Chupacabra - CR 3

New legendary creatures:
- Gishath, Sun’s Avatar - CR 10
- Zetalpa, Primal Dawn (Elder Dinosaur) - CR 30
- Nezahal, Primal Tide (Elder Dinosaur) - CR 30
- Etali, Primal Storm (Elder Dinosaur) - CR 30
- Tetzimoc, Primal Death (Elder Dinosaur) - CR 30
- Ghalta, Primal Hunger (Elder Dinosaur) - CR 30
- Zacama, Primal Calamity (Elder Dinosaur) - CR 30

Not sure if the legendary creatures are relevant for a character sheet, but I figured I'd pop the information here.

**Comment by Smashman** [comment]
Due to the race crossover, it might be worth updating Zendikar to 12.999 to ensure compatibility.

**Comment by Smashman** [comment]
I've made a start, as seen [here](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/pull/38).

Got to pop off now, but I intend to finish the rest by the end of the week, if you don't get there first. :slightly_smiling_face:

**Comment by morepurplemorebetter** [comment]
As I wrote for the pull request, I can't distribute any WotC material that is not explicitly part of the SRD.
