### ISSUE TITLE
UA sources are moved to Excl after new import file/manual

### ISSUE THREAD

**Issue by safety-orange** [morepurplemorebetter/MPMBs-Character-Record-Sheet#39]
If any of the UA sources are included and some are excluded, all of them are moved to excluded whenever a change is made to the imported scripts. This can be either to the manual imports or the file imports.

**Comment by morepurplemorebetter** [comment]
Thank you for reporting this issue. [It has been fixed now](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/commit/723cad55155999bb86edd9f2b376f8e42020b5f1) :)
