### ISSUE TITLE
Sheet hangs when changing half-drow racial options

### ISSUE THREAD

**Issue by jstrobush** [morepurplemorebetter/MPMBs-Character-Record-Sheet#4]
Issue: While building a character, I found myself in a situation where the sheet hung and never recovered. Restarting the sheet caused the racial options block to be blank, and any attempts to change this via the racial options button resulted in the same behavior.

Reproduction steps, starting with a new sheet: 

- Set character class (I used Paladin of the Crown 4 / Wild Sorcerer 2)
- Allow sheet to upgrade the characters experience (and abilities by extension)
- Do not allow a spell sheet to be generated at this time
- Set the Race to Half Elven
- Using the racial options button, choose "Drow Magic Half Elf"
- Choose another racial option (I used Fleet of Foot Half-Elf)

At this point the sheet will show its status as "Updating Half-Drow's Faerie Fire" and will never return.

Adobe Acrobat's JavaScript console logs the following error: 
```
TypeError: CurrentSpells[CurrentRace.known] is undefined
5668:Document-Level:Functions
```
Version information:

Sheet version: v12.87

Adobe Acrobat Reader DC
Version: 2015.023.20056
Architecture: x86_64
Build: 15.23.20056.213124
AGM: 4.30.67
CoolType: 5.14.5
JP2K: 1.2.2.37658

**Comment by morepurplemorebetter** [comment]
Thank you for reporting this issue. It hangs when switching from one racial variant to another, given that the first variant has spellcasting features at the current character's level.

I have fixed it [here](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/commit/6a23b0a70374f45ab532ce25da280871b5cffcaa#diff-bd12c4e008b90968b1dc176243324ff0R5668), which will be included in v12.88
