### ISSUE TITLE
Issues with new edits.

### ISSUE THREAD

**Issue by Slingshot128** [morepurplemorebetter/MPMBs-Character-Record-Sheet#44]
I was attempting to add the updated versions of the gunslinger archtype and the blood hunter class by matt mercer to my sheet but every time i tried, i got a few error messeges. Do note, i have added scripts before without issue, and i do have the version of the mpmb sheet required for the updates.

Error is as follows,

"ReferenceError: RequiredSheetVersion is not defined"

And if I remove the code line requiring the sheet version, i get this error.

"ReferenceError: FightingStyles is not defined"

No more errors occur if i remove both lines of code dealing with theses, but seeing as one is a feature and the other is for referencing the code. I feel like removing the code is not smart.

**Comment by morepurplemorebetter** [comment]
Thank you for reporting any issues you find with the sheet. Can you please elaborate on what you are doing exactly:

* Type of the sheet (printer friendly, redesign, colourful A4, colourful Letter);
* Version number of the sheet;
* The scripts you are trying to add (are they the latest versions from this repository)?
* With which script you are getting which error?
* How you are trying to import the script (as a file, copy-paste into the dialogue, run them from console)?

**Comment by morepurplemorebetter** [comment]
Looking at your errors again, I think you are using an older version of the sheet, older than v12.999. You do write "i do have the version of the mpmb sheet required for the updates", but fail to mention a version number, so there is no way for me to know if you are actually using v12.999 or some older version.

The files in this repo for Blood Hunter and Gunslinger are both for v12.999 of the sheet and don't work with older version. Please make sure you are using the latest version of the sheet. You can find it [here on ENworld](www.enworld.org/forum/rpgdownloads.php?do=download&downloadid=1180).

**Comment by Slingshot128** [comment]
I'm sorry that if I was not clear. Rereading the scripts i now see that i am indeed 1 version behind. I am running with v12 - 998. Unfortunately, being that the sheet was taken down from dmsguild, i don't have a way to access the newer version. I'm sorry for wasting your time.

**Comment by morepurplemorebetter** [comment]
I gave you a link to the latest version, but I see now the link wasn't working. The latest version of the sheets is found here: http://www.enworld.org/forum/rpgdownloads.php?do=download&downloadid=1180

**Comment by morepurplemorebetter** [comment]
The function RequiredSheetVersion() might have a lower number in it, but the comments at the start of the script clearly says it is meant for v12.999 of the sheet.

But you are right, it is confusing. I'll update all the scripts to say that they require v12.999 inside the RequiredSheetVersion() function, because the RequiredSheetVersion() function was introduced in v12.999 anyway :)

**Comment by Slingshot128** [comment]
https://gyazo.com/fd7150e566f7581ef06ff2ab54fa5d7c

I have gotten it working, but this is what i was meaning.

**Comment by morepurplemorebetter** [comment]
Fixed now, see for example: https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/blob/master/additional%20content/Classes/Blood%20Hunter%20%5BMatthew%20Mercer's%20work%2C%20transcribed%20by%20Darryl%20%26%20MPMB%5D.js
