### ISSUE TITLE
Attack Drop-Down Filtering Not providing Expected Results

### ISSUE THREAD

**Issue by rlugge** [morepurplemorebetter/MPMBs-Character-Record-Sheet#47]
First off, apologies if this is a duplicate.

When entering attacks (have seen this behavior before with feats, but not as bad), given the sheer number of available options, the drop down menu by itself is of limited utility.  The sheer number of options makes it painful to use.

You can type out the full name of an attack, and the autocomplete gets it 'right' for you.  Which is awesome.

I'm lazy.  I tend to use a mix of the two.  When you have the drop down open, and type the start of a name, it filters the list for me.  For example, if I type 'Sacred', 'Sacred Flame' is then the only available option.  I can then click on the filtered list to get to the item I want.

Current Behavior: When I click on an item, I *may* get what I was looking for, or I may get a psuedo-random result instead.   In this case, 'Sacred Flame' usually -- but not universally -- gets me a 'Scimitar' instead.
Expected behavior:  I should always get exactly what I was looking for.

**Comment by morepurplemorebetter** [comment]
This is a known issue with Adobe Acrobat DC and but something related to my sheets. As such, I can't change this behaviour. I suggest contacting Adobe about this issue.

**Comment by rlugge** [comment]
Oh.  Sorry to have bothered you then.
