### ISSUE TITLE
Feral Tiefling

### ISSUE THREAD

**Issue by BobbyByrne** [morepurplemorebetter/MPMBs-Character-Record-Sheet#5]
v12.87 Character sheet gets locked up when switching from regular tiefling and feral. The script loading box gets stuck at 'Updating Tiefling's Hellish Rebuke...'

Couple details about the scenario:
Level 4 Cleric, brand new fresh sheet,

**Comment by morepurplemorebetter** [comment]
Thank you for reporting yet another issue with the sheet!

This error is the same as issue #4 and has already been fixed in the code for sheet v12.88. However, that version of the sheet isn't published yet.

**Comment by BobbyByrne** [comment]
Awesome thanks :)
