### ISSUE TITLE
Issue with MPMB UA:RR Companion Sheet

### ISSUE THREAD

**Issue by goscinny** [morepurplemorebetter/MPMBs-Character-Record-Sheet#61]
When choosing a companion through the Companion Options button on the appropriate sheet we can choose between Ape, Black Bear, Boar, Giant Badger, Giant Weasel, Mule, Panther, and Wolf.

At a low level, the Black Bear has a proficiency bonus of +2 and a strength modifier of +2. In MPMB the Black Bear gets a -1 oProf modifier to its Attack (by clicking the Mod button) so it ends up with a +3 to attack. Is this -1 modifier a bug or not? The seven other companions do not have any negative modifier.

Absolutely love your product, thanks for all your work.

**Comment by morepurplemorebetter** [comment]
The attack for the Black Bear, according to the Monster Manual, is +3. However, this does not follow from adding its proficiency bonus (which is +2) to its Strength modifier (which is also +2). So there must be a -1 modifier somewhere. The sheet puts this in the attack modifier boxes, the monster manual simply never mentions it.
