### ISSUE TITLE
Class and Feats lists give an error when importing.

### ISSUE THREAD

**Issue by Bombermans** [morepurplemorebetter/MPMBs-Character-Record-Sheet#68]
It returns the following error: "SyntaxError: missing } after property list".

The version used is 12.999

**Comment by morepurplemorebetter** [comment]
Errors like the one you are describing on importing are with the script that is being imported, not with the sheet. The script you are trying to import is probably not part of this repository, although even if it was I couldn't tell from the limited information.

Please contact the person who wrote the script that you are trying to import and ask for a fix. If you wrote the script yourself or can't find the original author, I can recommend posting (a link to) the script on the [/r/mpmb subreddit](https://www.reddit.com/r/mpmb/), where people can help you with errors in your script.

Please only report issues here if you find something wrong with the code on this Git (i.e. the base functionality of the sheet, not with imported scripts).

**Comment by Bombermans** [comment]
Hello, sorry for my previous lack of more precise information. The scripts were downloaded from this repository:

The files were: 
 	Homebrew Syntax - ClassList.js 
and  
	Homebrew Syntax - FeatsList.js

from this link:
https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/tree/master/additional%20content%20syntax

**Comment by morepurplemorebetter** [comment]
You are correct, there were some missing commas in the syntax files. Another user has made a pull request that fixes this. Thus the files should now work.

Do note that importing the files will not do you any good as they are written up as an example for creating your own content. There are many more (game-mechanic) mistakes in them as they were not made to make sense, but just to serve as an example.
