### ISSUE TITLE
miss a "t" in cocktail

### ISSUE THREAD

**Issue by TheHangedGod** [morepurplemorebetter/MPMBs-Character-Record-Sheet#70]
https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/blob/79caf686dfb076509fe14e14cfa936d7241b9e08/additional%20content/Classes/Alchemist%20%5BDawnforgedCast's%20work%2C%20transcribed%20by%20PbFarmer%5D%20(incomplete).js#L470

**Comment by morepurplemorebetter** [comment]
Thank you for reporting this. As noted at the top of the code, I didn't write nor corrected this code so it is likely there are more of these inconsistencies.

This has now been fixed, [see here](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/commit/ef81f5a66ac0314953415fc43d1622d27cfeb186).
