### ISSUE TITLE
Level 2 Paladin does not invoke spellsheet creation

### ISSUE THREAD

**Issue by Shwaffle** [morepurplemorebetter/MPMBs-Character-Record-Sheet#76]
As reported here: https://www.reddit.com/r/mpmb/comments/a663cb/when_bringing_a_ranger_from_level_1_to_2_it/?ref=share&ref_source=link

**Sheet Version 13beta6**

When trying to upgrade to level 2 on a Paladin, the sheet does not automatically attempt to create a spellsheet. This behavior is working correctly for rogue, which also gets spellcasting at level 2.

**Comment by morepurplemorebetter** [comment]
Thank you for reporting this issue. I have implemented a fix for it ( d89f4bf37d1a7d7dd4ad7e6eeb2f9199aaf531b3 ) that will be part of the next beta.

The reason it is working for the Eldritch Knight and Arcane Trickster at level 3 (not 2) is that they also gain "Extra Spells" for which the functionality was working correctly.
