### ISSUE TITLE
Druid Air and Water Elemental Wild Shape Attack DCs incorrect

### ISSUE THREAD

**Issue by agentrfr** [morepurplemorebetter/MPMBs-Character-Record-Sheet#83]
Air Elemental Whirlwind should be DC 13 not 130
Water Elemental Whelm should be DC 15 not 150

:)

**Comment by morepurplemorebetter** [comment]
The DC is both listed in the CreatureList.js and it is calculated. As I don't see a 130 in the CreatureList.js, are you trying to say that the DC is calculated incorrectly? Where would that be, on the companion page or on the Wild Shape page?
If so, what version and type of the sheet are you using? Is this with v12.999?

**Comment by morepurplemorebetter** [comment]
I found the issue! It was only on the Wild Shape pages and only with attacks that use a DC, which not many wild shape options have.

Thank you for reporting it, I will make sure it is fixed in the next version of the sheet!
It is fixed with the commit 9d62eeec5849573b25e6a8ba2601a3eaf380233f
