### ISSUE TITLE
Issue when inserting or deleting rows in spellsheet with custom spells

### ISSUE THREAD

**Issue by L0neGamer** [morepurplemorebetter/MPMBs-Character-Record-Sheet#89]
I have a spell that isn't from any of the sources that are provided with the document, so I manually entered the details for it into my spell sheet. I then added some rows above it, and that row became cleared, so I filled it in again. When I then deleted an excess row above it, this newly filled in line became filled with the details from the spell above it.

I could not duplicate the latter effect when I tried again, but attached are two images of a before and after inserting a row.

![spellsheet1](https://user-images.githubusercontent.com/10566848/67144264-be9f2000-f26c-11e9-8882-876774e366c5.jpg)
![spellsheet2](https://user-images.githubusercontent.com/10566848/67144270-c19a1080-f26c-11e9-8ffc-9aeed5651821.jpg)

**Comment by morepurplemorebetter** [comment]
Do you have a version number for the sheet that this happens with? Can you walk me through how to reproduce it?
When inserting or deleting lines, the automation doesn't actually copy all the columns, only the hidden 'remember' column, which contains all the information to look up the spell in the dataset. If a spell is not in the dataset, it doesn't get any of the other columns filled out by the automation, thus effectively removing the spell.

**Comment by L0neGamer** [comment]
The version number is v13.0.0beta19.
Attached is a gif of what happens.
If the behind the scenes means that this is expected behaviour, then I guess this can either be marked as resolved or as a new requested feature.
If the gif doesn't explain the details sufficiently let me know and I'll try explain with words.

![examplespellsheet](https://user-images.githubusercontent.com/10566848/67146315-c0bfa980-f281-11e9-8ba0-a14544f4add9.gif)

**Comment by morepurplemorebetter** [comment]
I'm happy to report this issue has been fixed with commit 692e70e6d61e974d381b8236c3a6940601a31ed2 and you can expect v13.0.0beta21 to no longer erase manually added spell rows when inserting/deleting rows.

Also, manually changed spell headers, level dividers, and bluetext fields will be stored and moved as well
