### ISSUE TITLE
Weapon List - Damage: Character level + 1

### ISSUE THREAD

**Issue by mouse0270** [morepurplemorebetter/MPMBs-Character-Record-Sheet#9]
When creating a new Weapon List under damage you have this comment.
``` javascript
// Required; the damage it does. First entry is the amount of dice, second is the type of dice, and third is the damage type. This example is 2d4 worth of piercing damage. //if you want the amount of dice to be an amount determined by the Character Level, then put "C" as the first value. Alternatively, you can use "B" for the value minus 1 (such as with Green-Flame Blade)
```

When testing it I noticed that if I set `damage: ["C",6,"cold"]` that my damage type will calculate to `1d6` for the first 5 levels but then when I hit level 6 it will calculate to `2d6`.

Is it possible to get this to calculate to `2d6` for levels 1-5 and `3d6` for levels 6-11`, etc?

Currently I am doing `damage : ["C+1", 6, "slashing"],` and if this is the way I am supposed to be doing this, then you can just close this issue.

**Comment by morepurplemorebetter** [comment]
There is no inherent way for the sheet to calculate 1 more than the cantrip die for that level. The option to calculate one less is only added because the SCAG cantrips work like that.

You could edit the CalcAttackDmgHit function to add a third option, that is the cantrip die plus one, [see the code here](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/blob/master/_functions/Functions2.js#L5930).

Alternatively, you can define the weapons `damage` attribute as:
`damage: ["1d6+C",6,"cold"]`
Which will produce the result of 1d6+1d6 in the damage field. Not ideal, but conveys the information you want.

**Comment by mouse0270** [comment]
Alright, so here is what I got working in a really quick.

Basically right after line 5933 I added
``` javascript
if ((/(d)/).test(output[out])) {
	output[out] = eval(output[out].split('d')[0]) + 'd' + eval(output[out].split('d')[1]);
}else{
	output[out] = eval(output[out]);
}
```

With the about 30 minutes of testing I have done this appears to be working pretty well. It even removes your need for `B` because you could just write `C-1d10`

I am going to try an improve it, but it is working for my needs now. Just wanted to share in case this is something you would like to add in the future.

**Comment by morepurplemorebetter** [comment]
Thank you for sharing!

Your code will work for most weapon damage's, as they do a single die. But for a damage like that of Green-flame Blade (1d8/2d8) your code will result in an error. And some creature attacks have damage as "Grappled", which will also result in an error.

**Comment by mouse0270** [comment]
Yeah, that is what I am fixing now. 

Do you know of a creature attack that has damage as grappled so I can take a look and patch those and make a pull request?

**Comment by morepurplemorebetter** [comment]
[The Giant Spider's Web attack is one of them.](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/blob/master/_variables/ListsCreatures.js#L2180)

**Comment by mouse0270** [comment]
So I can't seem to fork this form some reason. But this is the code I am using, it appears to be working pretty decently with all of my tests.

``` javascript
if ((/(B|C)/).test(output[out])) { //if this involves a cantrip calculation
	var cLvl = Number(QI ? What("Character Level") : What(prefix + "Comp.Use.HD.Level"));
	var cDie = cantripDie[Math.min(Math.max(cLvl - 1, 1), 19)];
	var mouse0270Dice = output[out].replace(/C/g, cDie).replace(/B/g, cDie - 1).replace(/0.?d\d+/g, 0);

	output[out] = mouse0270Dice.split("/").map(function(v) { 
		return v.split("d").map(function(c) {
			return eval(c);
		}).join('d')
	}).join('/');
};
dmgDie = output[out];
```

**Comment by morepurplemorebetter** [comment]
Unfortunately, that will also produce a heap of errors. Take the Eldritch Blast attack entries for example, they are written as
'C×1d10'

And if somebody wrote damage like
'Cd6+1d8'
it would be converted to
'1d7d8'

Or if somebody wrote damage like
'Bd6+C'
it would be converted to
'0d7'

**Comment by mouse0270** [comment]
The first one is easy to solve for. That's a simple find and replace. Also I don't think that would throw an error it just wouldn't calculate for that instance.

For the rest what I could do is get the weapon and the. Get the damage and only calculate on the first part of the array and rebuild the damage die that way. However doing that would break slot more things in your script... Give me a few more days. I am sure I'll think of something

**Comment by mouse0270** [comment]
You wouldn't have examples of those last ones already happening or should I just create a few fake weapons for testing.

**Comment by morepurplemorebetter** [comment]
The last two are just examples of what might be possible and everything that is possible shouldn't be able to generate an error or the whole sheet will stop working. You can get around that by adding a `try { } catch( ) { }` around the eval you are using. However, I'm still not convinced that any of this is really a good idea, because sometimes you might want the thing to display exactly what you are typing, and not some permutated version of it.

Instead of making new weapons, why not just run the piece of code you are working on in a JSfiddle. I quickly made one here:  https://jsfiddle.net/ry0hvdf2/ with the following code:

```javascript
//put what you want to test in this variable
[ "Cd8+Bd8",
	"Cd8×Bd8",
	"Cd8-Bd8",
].forEach(function(input) {testCode(input)});

function testCode(input) {
  var out = "out"; var output = {out : input}; var cLvl = 6;
  var cantripDie = [1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4];
	
  try {
    //the code that is used
    if ((/^(?=.*(B|C))(?=.*d\d).*$/).test(output[out])) { //if this involves a cantrip calculation
      //var cLvl = Number(QI ? What("Character Level") : What(prefix + "Comp.Use.HD.Level"));
      var cDie = cantripDie[Math.min(Math.max(cLvl - 1, 1), 19)];
      output[out] = output[out].replace(/C/g, cDie).replace(/B/g, cDie - 1).replace(/0.?d\d+/g, 0);

      output[out] = output[out].split("/").map(function(v) { 
        return v.split("d").map(function(c) {
          return eval(c);
        }).join('d')
      }).join('/');
    };
    
    var theOut = output[out];
   } catch(err) {
   	var theOut = err;
   }

	console.log("The output for '" + input + "' is: '" + theOut + "'.");
};
```

Just open your browser's console, the result will be posted there.

**Comment by mouse0270** [comment]
so something more like this.

``` javascript
        output[out] = output[out].split("/").map(function(v) {
        	var a = v.split("d");
          a[0] = eval(a[0]);
          return a.join('d')
        }).join('/');
```

**Comment by mouse0270** [comment]
Unrelated to this topic, way is `Agonizing Blast` damage set to `["C\u00D7" + 1, 10, "force"]` instead of `["C", 10, "force"]`

The first one outputs `2x1d10` where the second one outs puts `2d10`

This question is just to try and better my understanding.

**Comment by morepurplemorebetter** [comment]
I don't think this second version is any different with handling the erroneous cases :S

The Eldritch Blast cantrips (so including Agonizing Blast, Eldritch Spear, and Agonizing Spear) all are written as C×1d10+Cha to indicate that each d10 is its own ray and that if you shoot the rays at different targets, you get the charisma damage added to each.

**Comment by mouse0270** [comment]
That first part was it towards the script or my question?

As for the eldritch blast info. That makes perfect sense, I just wasn't sure on the reasoning. Now that you have explained it, it does make sense why it is written that way.

**Comment by morepurplemorebetter** [comment]
The first part was regarding the code you put two comments back:
``` javascript
        output[out] = output[out].split("/").map(function(v) {
        	var a = v.split("d");
          a[0] = eval(a[0]);
          return a.join('d')
        }).join('/');
```

**Comment by mouse0270** [comment]
You are probably right that the output split would still probably have issues calculating the erroneous cases, but that is why I wrapped it in that `try { } catch {}` basically if it does run into in issue trying to calculate it will end up using the format that you are using now, which is to just display the information as plain text.

**Comment by morepurplemorebetter** [comment]
Ah, I see now that you put a `try { } catch( ) { }` around the code in the merge request, but I was going off what you posted here, which does not include the `try { } catch( ) { }`. However, things like "1+1d10" will still result in an unwanted "2d10".

**Comment by mouse0270** [comment]
Why is `1+1d10` not supposed to result in `2d10`?

That is what I would expect it to result in.

**Comment by morepurplemorebetter** [comment]
For example, if you have some ability that adds a 1d10 to your unarmed strike's damage of 1. This is the case for a barbarian in one of the campaigns I play, and that player likes to write it as `1+1d10` this then gets made to `1+1d10+4` by the code when adding his Strength bonus. Sure, it is some homebrew thing and he could write it as `1d10+1`, but I fully understand that reading `1+1d10+4` is easier than `1d10+1+4`.

**Comment by mouse0270** [comment]
Updated pull request.

**Comment by morepurplemorebetter** [comment]
I like the idea of using the "=" as an indicative character. Unfortunately, the fields for putting in the damage dice (and thus this calculation that you are proposing) aren't really big and you won't be able to put much more than 5-6 characters there, so this has very limited usability for anybody not adding the weapons as code.

Anyway, I made some changes and came up with this, instead of using your pull request (which isn't possible anymore as there is a conflict):

```javascript
if (output[out][0] == "=") { // a string staring with "=" means it wants to be calculate to values
	output[out] = output[out].substr(1).split("d").map(function(v) {
		try {
			return eval(v);
		} catch (errV) {
			return v;
		};
	}).join("d");
};
```

**Comment by mouse0270** [comment]
Looks good to me, yeah I was trying to find a way to resolve the conflict.

I think most people who use your form try to avoid turning on the modifiers unless they have to. haha. I think the calc will be used for more homebrew things using your very flexible content system.
