### ISSUE TITLE
Deleting a Spell Sheet row does not delete it

### ISSUE THREAD

**Issue by L0neGamer** [morepurplemorebetter/MPMBs-Character-Record-Sheet#90]
After reviewing the latest changes in the 13.0.0beta21 sheet (Using the Printer Friendly Redesign) I decided to import a sheet from a previous version, that was having the issues discussed [here](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/issues/89).

However, when trying to delete a row, nothing seems to happen.

Below are example gifs of me trying to delete various rows. The first is an empty row. The second is a row that was auto-filled. The third is a row that had custom data in the first column; in the last one, I also selected what text I could from the other test cases, demonstrating that the data was somewhat present at least.

![spellsheetdelete1](https://user-images.githubusercontent.com/10566848/68094288-b662f980-fe96-11e9-9308-d133b797fb16.gif)

![spellsheetdelete2](https://user-images.githubusercontent.com/10566848/68094286-b662f980-fe96-11e9-96ea-97aff5c993a2.gif)

![spellsheetdelete3](https://user-images.githubusercontent.com/10566848/68094287-b662f980-fe96-11e9-8b9d-19d428f5c363.gif)

**Comment by morepurplemorebetter** [comment]
Thank you for reporting this issue!
I have fixed it in this commit: 0369160d90b56615be542f3c076023d8a98ebb14
