### ISSUE TITLE
Export/Import

### ISSUE THREAD

**Issue by m42e** [morepurplemorebetter/MPMBs-Character-Record-Sheet#92]
Is there any plan to export/import to a text based format just as json or yaml?

Would really like to have something like that so that I do not have to have so much data duplicated.

Thanks a lot

**Comment by morepurplemorebetter** [comment]
This is more a feature request than an issue with the code in this repo. Feature requests can be made over on the Discord channel. An invite link to the Discord channel can be found in the 'About' section on [my Patreon page](https://www.patreon.com/morepurplemorebetter).
